#ddev-generated
---
services:
  arangodb:
    container_name: "ddev-${DDEV_SITENAME}-arangodb"
    image: arangodb/arangodb:3.10.2
    user: ${DDEV_UID}:${DDEV_GID}
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8529:8529
      - ARANGO_NO_AUTH=1
      - ARANGO_ROOT_PASSWORD="db"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    volumes:
      - ".:/mnt/ddev_config"
      - "..:/var/www/html"
      - arangodb3data:/var/lib/arangodb3
      - arangodb3apps:/var/lib/arangodb3-apps
volumes:
  arangodb3data:
    name: "${DDEV_SITENAME}-arangodb3data"
  arangodb3apps:
    name: "${DDEV_SITENAME}-arangodb3apps"
